### ISSUE TITLE
TA-Lib installation failing(Mac OS) - /use/include -operation not permitted or file system is read only.

### ISSUE THREAD

**Issue by dalwindr** [TA-Lib/ta-lib-python#582]
Hi team,
getting following error while using pandas TA
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/48798210/224527216-416e4caa-b5f1-4422-a613-a08a91f03a79.png">

What i did?how i installed this lib

1. mkdir /Users/apple/talib
2. mkdir  /Users/apple/talib/include
3. copy ta-lib /Users/apple/talib/ta-lib
4. cd /Users/apple/talib/ta-lib
5. ./configure --prefix=/Users/apple/talib/include
6. make
7. sudo make install
8. export PREFIX=/Users/apple/talib/include
9. export TA_LIBRARY_PATH=$PREFIX/lib
10. export TA_INCLUDE_PATH=$PREFIX/include
11.  pip3 install TA-Lib

All the steps from 1 to 11 got succeeded but getting following error given in the image.

I believe the issue is pandas is trying to load libs from /use/include and li configured these libs in /Users/apple/talib/include

I have macOS, It is not allowing to create any file/directory in /usr, it is strickly restricted and it is mounted as Read only file system and 
No there is no option or way to allow mac to make new file/directory creations in /usr.
 i already tried following option but did not work.
          1. mac os recovery terminal 
          2. mac security with disk full access terminal

Hope you understood the context and issue.

Now query is..
Can we configure TA-lib to load lib from /Users/apple/talib/include and not from /use/include ?

**Comment by mrjbq7** [comment]
Have you tried “python3.9 -m pip install ta-lib”?Sometimes pip3 is pointing to a different python. Why not use homebrew to install?It’s odd that it’s looking for /usr/lib.On Mar 12, 2023, at 11:44 AM, dalwindr ***@***.***> wrote:﻿
Hi team,
getting following error while using pandas TA

What i did?how i installed this lib

mkdir /Users/apple/talib
mkdir  /Users/apple/talib/include
copy ta-lib /Users/apple/talib/ta-lib
cd /Users/apple/talib/ta-lib
./configure --prefix=/Users/apple/talib/include
make
sudo make install
export PREFIX=/Users/apple/talib/include
export TA_LIBRARY_PATH=$PREFIX/lib
export TA_INCLUDE_PATH=$PREFIX/include
pip3 install TA-Lib

All the steps from 1 to 11 got succeeded but getting following error given in the image.
I believe the issue is pandas is trying to load libs from /use/include and li configured these libs in /Users/apple/talib/include
I have macOS, It is now allowing to create any file/directory in /use , it is strickly restricted and it is mounted as Read only file system and No there is no option or way to allow mac to these creations.
How you understand the context
Now query,
Can we configure TA-lib to load lib from /Users/apple/talib/include and not from /use/include ?

**Comment by dalwindr** [comment]
Thanks Home brew worked for me

**Comment by mrjbq7** [comment]
Good.

Your way *should* have worked, I’m not sure why it didn’t.
